Modules/Classification/CLLibSVM/src/svm.cpp
Modules/Core/files.cmake
Modules/Core/include/mitkLocaleSwitch.h
Modules/Core/src/IO/mitkDicomSeriesReader.cpp
Modules/Core/src/IO/mitkDicomSeriesReaderService.cpp
Modules/Core/src/IO/mitkItkImageIO.cpp
Modules/Core/src/IO/mitkLocaleSwitch.cpp
Modules/Core/src/IO/mitkSurfaceStlIO.cpp
Modules/DICOMReaderServices/src/mitkBaseDICOMReaderService.cpp
Modules/DiffusionImaging/DiffusionCore/autoload/IO/mitkDiffusionImageNiftiReaderService.cpp
Modules/DiffusionImaging/DiffusionCore/autoload/IO/mitkDiffusionImageNiftiWriterService.cpp
Modules/DiffusionImaging/DiffusionCore/autoload/IO/mitkDiffusionImageNrrdReaderService.cpp
Modules/DiffusionImaging/DiffusionCore/autoload/IO/mitkDiffusionImageNrrdWriterService.cpp
Modules/DiffusionImaging/DiffusionCore/autoload/IO/mitkNrrdQBallImageReader.cpp
Modules/DiffusionImaging/DiffusionCore/autoload/IO/mitkNrrdQBallImageWriter.cpp
Modules/DiffusionImaging/DiffusionCore/autoload/IO/mitkNrrdTensorImageReader.cpp
Modules/DiffusionImaging/DiffusionCore/autoload/IO/mitkNrrdTensorImageWriter.cpp
Modules/DiffusionImaging/DiffusionCore/src/DicomImport/mitkDicomDiffusionImageHeaderReader.cpp
Modules/DiffusionImaging/DiffusionCore/src/DicomImport/mitkGEDicomDiffusionImageHeaderReader.cpp
Modules/DiffusionImaging/DiffusionCore/src/DicomImport/mitkSiemensDicomDiffusionImageHeaderReader.cpp
Modules/IGTBase/autoload/IO/mitkNavigationDataReaderCSV.cpp
Modules/IGTBase/autoload/IO/mitkNavigationDataReaderXML.cpp
Modules/IGTBase/autoload/IO/mitkNavigationDataSetWriterCSV.cpp
Modules/IGTBase/autoload/IO/mitkNavigationDataSetWriterXML.cpp
Modules/IOExt/Internal/mitkParRecFileReader.cpp
Modules/LegacyIO/mitkDataNodeFactory.cpp
Modules/LegacyIO/mitkImageWriter.cpp
Modules/LegacyIO/mitkItkImageFileReader.cpp
Modules/PlanarFigure/src/IO/mitkPlanarFigureReader.cpp
Plugins/org.mitk.gui.qt.dicom/src/internal/DicomEventHandler.cpp

Calls like 
```
const char* previousCLocale = setlocale(LC_NUMERIC, nullptr);
setlocale(LC_NUMERIC, "C");
```
are invalid because `previousCLocale` variable becomes invalid after the second `setlocale() `call.
https://msdn.microsoft.com/ru-ru/library/x99tb11d.aspx:
"Later calls to setlocale overwrite the string, which invalidates string pointers returned by earlier calls."
This may lead to random crashes.
It's possible to reproduce such crash if run debug version of program under Application Verifier with Basics.Heaps option enabled.
Signed-off-by: KuznetsovAlexander <KuznetsovAlexander@rambler.ru>

Used mitk::LocaleSwitch to change locale

---

Modules/QtWidgets/src/QmitkDataStorageTreeModel.cpp

QmitkDataStorageTreeModel accepts "application/x-qabstractitemmodeldatalist" format.
It's general tree data item format that means that QmitkDataStorageTreeModel accepts almost any item from any QTreeWidget.
But later QmitkDataStorageTreeModel casts data items to "application/x-qmitk-datastorage-treeitem-ptrs" and if cast fails, ToTreeItemPtrList() returns empty list. When accessing the first element of this empty list, crash occurs.
I can't reproduce this crash in MITK because I didn't find the second tree widget but I encountered this in our MITK fork.
Now there is a check on list's size before using it.
Signed-off-by: KuznetsovAlexander <KuznetsovAlexander@rambler.ru>

Fixed drag-and-drop crash in data manager

---

Modules/Core/include/mitkPlaneGeometry.h
Modules/Core/include/mitkSlicedGeometry3D.h
Modules/Core/src/Algorithms/mitkPlaneGeometryDataToSurfaceFilter.cpp
Modules/Core/src/DataManagement/mitkPlaneGeometry.cpp
Modules/Core/src/DataManagement/mitkSlicedGeometry3D.cpp
Modules/Core/src/Rendering/mitkPlaneGeometryDataVtkMapper3D.cpp
Modules/Segmentation/Algorithms/mitkDiffSliceOperation.h

Signed-off-by: Miklos Espak m.espak@ucl.ac.uk

SlicedGeometry3D::GetReferenceGeometry() function for API consistency

---

Modules/Core/src/Rendering/mitkVtkPropRenderer.cpp
Modules/QtWidgets/src/QmitkStdMultiWidget.cpp

Then the data storage of a renderer is set, a bounding box is calculated
from the currently visible data nodes in the data storage, and the renderer
is updated. The setters do not check if the 'new' data storage is the same
as the current one, which results that the bounding box is recalculated
and the renderer is updated again, unnecessarily.
This changes adds a check to the setters to skip the update if the data
storage is the same.
The data storage is set from the constructor of the renderer (to the data
storage of the rendering manager), and it is also set by explicit
SetDataStorage calls after the renderers have been constructed. Ideally,
the repeated calls to the setter should be eliminated, but with this
change the repeated calls will return immediately, at least.
Signed-off-by: …

Equality checks when setting data storage for renderers

---

Modules/AppUtil/include/mitkBaseApplication.h
Modules/AppUtil/src/mitkBaseApplication.cpp

- Added a configuration option which allow to give an image
filename used as splash screen
- Added a inner QRunnable which allow CTK to close the splash
screen once the platform is started
Signed-off-by: Aurélien Labrosse aurelien@pollen-metrology.com

fix for bug 19635

---

Plugins/org.mitk.gui.qt.dosevisualization/src/internal/RTDoseVisualizer.cpp

ModalityIsRTDose() is called on node change.
But if there is no data in node or data doesn't have "modality" property, there will be access violation and crash.

Fix crash in RT Dose Visualization

---

Modules/Segmentation/Interactions/mitkRegionGrowingTool.cpp

This problem is described in https://phabricator.mitk.org/T22494
There is a problem in region growing: screen difference coordinates are modified on mouse moving but they are never reset:
m_ScreenYDifference += positionEvent->GetPointerPositionOnScreen()[1] - m_LastScreenPosition[1];
m_ScreenXDifference += positionEvent->GetPointerPositionOnScreen()[0] - m_LastScreenPosition[0];
This leads to problems after several tool usages.
If you always move mouse in one direction when selecting several regions with region growing, m_ScreenYDifference and m_ScreenXDifference become huge, thresholds for tool become huge, too, and tool works incorrectly.
I've added coordinate difference reset on mouse button release.
Signed-off-by: KuznetsovAlexander <KuznetsovAlexander@rambler.ru>

Fixed coordinate difference in region growing

---

Modules/Core/resource/Interactions/DisplayInteraction.xml

This commit fixes 2 bugs:
- Stuck in crosshair rotation, as explained in T22464.
- Stuck with the wrong cursor, if you move your cursor following an
axis out of the render window, the cursor doesn't revert to the
standard cursor, so you can have a rotation cursor in the 3D view,
in the datamanager, etc.
Signed-off-by: Nil Goyette <nil.goyette@imeka.ca>

Fix crosshair rotation cursor

---

Plugins/org.blueberry.ui.qt.help/src/internal/berryHelpWebView.cpp
Plugins/org.blueberry.ui.qt.help/src/internal/berryHelpWebView.h

Simple fix of the message that is displayed when the context help view does not find the corresponding HTML page.
Distinguish between missing help pages and missing help context (context can be fixed by user)
Signed-off-by: Daniel Maleike <code@maleike.de>

Distinguish between missing help pages and missing help context

---

Modules/DiffusionImaging/FiberTracking/IODataStructures/FiberBundle/mitkFiberBundle.cpp
Modules/DiffusionImaging/FiberTracking/IODataStructures/FiberBundle/mitkFiberBundle.h

Only a const correctness fix: add more const and use itkGetConstMacro instead of itkGetMacro. I don't see how it could break anything.
Signed-off-by: Nil Goyette nil.goyette@imeka.ca

More const methods in FiberBundle

---

Plugins/org.mitk.gui.qt.datamanager/src/QmitkDataManagerView.cpp

Retrieving icon by doing QIcon(iconPath) works only when the icon is a
resource of the same plugin, so only icons of the DataManager plugin were
found. This fix enables getting ions from other plugins (requested by
plugin.xml).
Signed-off-by: Nil Goyette <nil.goyette@imeka.ca>

Find icons in contextMenuAction extension point

---

Plugins/org.blueberry.core.runtime/src/internal/berryInternalPlatform.cpp

Two bugs in berry::InternalPlatform:
1. confusion between service variables installLocation and instanceLocation,
2. locations are not closed correctly that gives a segfault when the application closes.
Important: to have the functionality, there is also a correction in ctk to apply (cf. https://github.com/commontk/CTK/pull/719). The second bug can be seen only after applying the ctk correction, without it InternalPlatform cannot find locations at all (all pointers are null).

Correction to be able to retrieve ctk locations via berry::Platform

---

Modules/DiffusionImaging/FiberTracking/Algorithms/itkStreamlineTrackingFilter.h

When compiling in Debug in Visual Studio 2015 the compilation fails in line 112 of itkStreamlineTrackingFilter.h. This is the following line:
itkSetMacro( SeedPoints, std::vector< itk::Point<float> >)
In Debug itkSetMacro tries to print a message using itkDebugMacro. It streams the std::vector to a std::ostringstream. In this context there is no overloaded << operator for std::ostream, so it does not compile. I think the best solution is to write a setter for that vector manually, not using the itk macro.
Signed-off-by: Federico E. Milano <fmilano@gmail.com>

T23055 fixes the itkSetMacro for std::vector parameter

---

Modules/Segmentation/Interactions/mitkBinaryThresholdTool.cpp

Image with intensity in range [0.0, 1.0[ crashed the segmentation plugin because the BinaryThresholdImageFilter received a low value greater than the high value. There's a better explnanation in the [bug report](https://phabricator.mitk.org/T22870).
Signed-off-by: Nil Goyette <nil.goyette@imeka.ca>

Fix crash on Threshold

---

Modules/QtWidgets/src/QmitkDataStorageTreeModel.cpp
Plugins/org.mitk.gui.qt.datamanager/src/QmitkDataManagerView.cpp

When the data manager was initialised from a data storage or when
new data nodes were added, the nodes were added to the top or the
bottom under their source nodes, depending on the value of the
"Place new nodes on top" preference.
Beside this, when the data manager was initialised, the data nodes
were added in the same order in which they appeared in the data
structure retrieved from the data storage. However, in this data
structure the nodes are ordered by their smart pointer what makes
the final order in the data manager indeterministic.
The current commit inserts the nodes at the position according to
their layer, unless the the preference is set, in which case it
inserts the nodes at the top. This is when adding new nodes to the
data storage. When initialising the data manager from a …

Nodes are inserted in data manager at position according to their layer

---

Modules/IGT/IO/mitkNavigationToolReader.cpp
Modules/IGT/IO/mitkNavigationToolWriter.cpp

Serializes all the properties of the associated DataNode and reads all the properties in a tool serialized file.
Signed-off-by: Federico Milano <fmilano@gmail.com>

Serializes and deserializes the complete DataNode associated with a NavigationTool.

---

Modules/IGT/Common/mitkSerialCommunication.cpp

Replaced GetLastError Win32 API calls by ERROR_VALUE, to avoid inconsistent return values, since OK is defined as 1 and ERROR_VALUE as 0 in mitkSerialCommunication.
Signed-off-by: Federico Milano <fmilano@gmail.com>

Replaced GetLastError Win32 API calls by ERROR_VALUE in mitkSerialCommunication

---

Modules/Gizmo/src/mitkGizmoInteractor.cpp
Modules/Gizmo/src/mitkGizmoMapper2D.cpp

When moving an object with direct manipulation (gizmo) along a single axis sometimes the controls reverse and the object moves up when dragging down, left when dragging right, etc.
Able to reproduce this issue after turning the object upside down with the rotation provided by direct manipulation.
In addition, 2D display does not scale well depending on the current zoom factor.
Both behaviors were fixed in the two commits provided. Displacement calculation was wrong, 2D rendering did not consider zoom factor.

Fix gizmo display and moving

---

Plugins/org.blueberry.ui.qt/src/internal/berryWorkbenchWindow.cpp

Behavior observed on Windows when workbench window is completely on a second screen (not the default screen) and restored the next time that workbench ist started: the window would be displayed with a very small (~20px) width and the titlebar out of reach because above the screen top limit.
Debugging into this brought me to the changed file which applies some logic if the previously stored window position has no overlap with the default screen geometry. This would trigger for the second screen scenario above.
I changed the behavior so that the window will be centered in a
default size of 90% when it does not show on the default screen.
This avoids unusable tiny window sizes.
I would have preferred to restore the original position on the second screen, but this would have required deeper …

When the workbench window is out of the (default) screen, center it.

---

Modules/QtWidgets/src/QmitkIOUtil.cpp

Per default the Data Manager's "Save..." option via QmitkIOUtil proposes the DataNode's name as the filename. When the node name is "a:b" or simliar, this might produce files that are empty and named slightly different (in the example "a" instead of "a:b.obj"). The problem is that file systems do not accept all characters (esp. Windows)
Without a in QmitkIOUtil writers might (and some do) create empty files
that are not even named as expected (e.g. "a" instead of "a:b.obj").
The opening of a std::ofstream for such a filename does not seem to set
any fail-bits (all checked for in the affected writer class). So even writers that correctly check for the output stream state won't notice the problem.
The alternative to a check here would be a check in each possible writer class. This seems …

Check filename for invalid characters before saving e.g. "a:b.obj"

---

CMakeLists.txt

Qt 5.12.x is required but cmake forbids
versions greater than 5.12.0.

Fix build error for Qt 5.12.x.

---

CMakeExternals/VTK-8.1.0.patch
CMakeExternals/VTK.cmake
Modules/Core/include/mitkVtkPropRenderer.h
Modules/Core/include/vtkMitkRenderProp.h
Modules/Core/src/Rendering/mitkVtkPropRenderer.cpp
Modules/Core/src/Rendering/vtkMitkRenderProp.cpp

VTK has a nice way of handling translucent polydata objects which does not work in MITK: depth peeling [1] [2]. This change makes translucent rendering work again.
To enable depth peeling, one would need to initialize a render window as documented:
```
renderWindow->SetAlphaBitPlanes(1);
renderWindow->SetMultiSamples(0);
renderer->SetUseDepthPeeling(1);
renderer->SetMaximumNumberOfPeels(100);
renderer->SetOcclusionRatio(0.1);
```
Doing so in MITK will result in surfaces with opacity < 1 looking horribly bright. Tracing down, this is because VTK rendering provides a vtkInformation object to all rendered vtkProps. MITK breaks this because its primary vtkProp `vtkMitkRenderProp` does not forward this information object to all the mitk::VtkMapper generated vtkProps.
This patch enables …

Forward vtkInformation objects to MITK mappers - enable VTK depth peeling

---

Modules/Core/include/mitkPointSetVtkMapper2D.h
Modules/Core/src/Rendering/mitkPointSetVtkMapper2D.cpp

Added an option to render point set markers as fixed-size glyphs on the
screen to improve visualization at very high zoom levels. When this
option is turned on, marker sizes are interpreted in screen pixels
rather than world coordinates.
Signed-off-by: Sven J Lafebre <s.lafebre@runbox.com>

T28616: Add option to visualize point sets as fixed-size markers

---

Plugins/org.mitk.gui.qt.mitkworkbench.intro/resources/WelcomePresentation.html

'Specifying the same attribute twice on the same HTML element is redundant and may indicate a copy-paste mistake.'
Signed-off-by: luz paz <luzpaz@github.com>

Fix 'duplicate HTML element attributes' reported by LGTM

---

CMakeExternals/ITK.cmake

ITK 5.4.0 suffers from a compiler error concerning a duplicated `__ucrt_int_to_float` symbol with current MSVC compiler versions.
The most recent version ITK 5.4.2 includes a fix for this via [this](https://github.com/InsightSoftwareConsortium/ITK/pull/4958) PR.
I'd suggest to update ITK so that MITK compiles with current MSVC versions.

Update ITK to 5.4.2 to fix libtiff duplicate compiler error on newer MSVC versions
